### ISSUE TITLE
Miro stickies pack - save & create button

### ISSUE THREAD

**Issue by Altuition** [fredcido/miro-stickies-pack#16]
I really liked the new Miro feature 'Stickies pack'. 
Unfortunately the save and create button is not visable anymore.

**Comment by fredcido** [comment]
Hey @Altuition , thanks for the feedback.
What do you mean by the `Save and create` button is not visible anymore? Can you provide a screenshot?
<img width="375" alt="image" src="https://github.com/fredcido/miro-stickies-pack/assets/7162412/5532a27c-2bb2-478b-9a8b-db81d461c542">

**Comment by fredcido** [comment]
Fixed by https://github.com/fredcido/miro-stickies-pack/commit/6fe8614b040b1dacbcacf7c83607573abb51cb2a
